### ISSUE TITLE
Example: Provide really basic physics, player movement demo

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#160]
Using the bvh as a static world

**Comment by gkjohnson** [comment]
Possible levels with CC license:

- https://sketchfab.com/3d-models/low-poly-environment-jungle-scene-b07cbb11f78b43a3a51405e6c77a629e
- https://sketchfab.com/3d-models/low-poly-game-level-82b7a937ae504cfa9f277d9bf6874ad2

**Comment by gkjohnson** [comment]
### TODO
- [ ] Properly impart velocities on sphere collision accounting for mass
- [ ] Small optimization
- [ ] Add collision animation
- [ ] Add first person controller
