### ISSUE TITLE
Remove the non-compact BVH representation

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#187]
Maintaining both the compact and the class-based representation of the bounds tree is complex and limiting. And generating the tree in a webworker means any added overhead of producing the buffer can be offloaded.

Related to #186 and #99 which require some more complex changes to the inner workings of the BVH class.

**TODO**
- [x] Remove "lazyGeneration" flag entirely.
- [x] Update documentation for webworker generation so it's more clear as an option, though it won't necessarily work out of the box.
- [x] Remove conditional cases buffer and non buffer traversal variant (and therefore "packData" option)
- [x] Clean up buffer cast functions
- [x] Benchmark performance difference.
- ~Provide a helper to generate a more human-readable object form of the packed buffer contents~ See `MeshBVHDebug.getJSONStructure`.
