### ISSUE TITLE
Raycaster.firstHitOnly is missing a closest raycast

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#269]
When testing the "coffeemat" model there's a section where the closest hit is not retrieved when raycast.firstHitOnly === true:

Specifically on this handle thing:

![image](https://user-images.githubusercontent.com/734200/126047874-be8ae51b-3780-4725-94a5-376034d67ebd.png)

These are the distance differences when using firstHitOnly = false vs true:

![image](https://user-images.githubusercontent.com/734200/126047891-fa22231e-bf8f-4d50-8413-f158bae5891b.png)

**TODO**

- [x] Adjust the raycast.html example to repro the issue every time
- [ ] Track down the issue
- [ ] Make minimum repro case
- [ ] Add test

**NOTES**

- Seems to be related to the `leftToRight` bounds order check. Inverting it yields correct result
- Also setting isOutside to always be false fixe the issue, as well.

**Comment by gkjohnson** [comment]
The issue is that this point being used to determine whether to run the next sibling is in world space rather than local space like the bounds:

https://github.com/gkjohnson/three-mesh-bvh/blob/9a412aa54dd9c9333b3ebad4f3a2b3159371cbdd/src/castFunctions.template.js#L132
