### ISSUE TITLE
Consider storing a separate triangle index buffer instead of reordering the triangle index array

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-mesh-bvh#294]
Instead of reordering the geometry index array we can create a new index buffer _into_ the existing geometry indices (or directly into the vertex attributes) which would remove the need to rearrange the existing indices.

Pros:
- More flexible because existing cached triangle indices would no longer be invalidated on rebuild.
- Not rearranging the index buffer means geometry groups would no longer have to be split into multiple roots.
- _Possibly_ faster to build because the sorting / partitioning logic would be simpler.

Cons:
- Likely slower raycasting due to more indirection.
- More memory (1-4 more bytes per triangle depending on geometry size).
- Material indices from groups would have to be derived afterward by iterating over groups.

Open Question:
- What to do if no index has been generated? Just generate an increasing one? (or just assume it's constantly increasing?)
- What's the performance impact?

Perhaps a different build option could be provided so both are viable?

**Comment by gkjohnson** [comment]
Changes required to support an option:

- Index no longer has to be ensured (`buildTree` function)
- Instead of bookkeeping an index array we keep an indirect "triangleIndex" array that is 1/3 the size (`buildTree` function)
- "partition" function needs to sort an array that is 1 / 3 the size (`partition` function)
- "raycast" function needs to be adjusted to take an indirect array or take function for running intersections (`raycast` cast function)
- "raycastFirst" function needs to be adjusted to take an indirect array or take function for running intersections (`raycastFirst` cast function)
- "shapecast" functions needs to be adjusted to take an indirect array or it can be wrapped in MeshBVH call (`MeshBVH.shapecast` or `shapecast` cast function)

**Comment by McCulloughRT** [comment]
This was an important feature for me, so I forked and took a stab at it in my ["indirect-triangle-index" branch](https://github.com/McCulloughRT/three-mesh-bvh/tree/indirect-triangle-index)

It covers most of what you've laid out, except I haven't looked into "shapecast" yet. I also opted to change "intersectTri" in ThreeRayIntersectUtils instead of the "raycast" and "raycastFirst" functions.

Happy to submit a PR if desired!

**Comment by gkjohnson** [comment]
Hey @McCulloughRT! This is great -- thanks for taking a stab at it. If you're interested in taking it to the finish line go ahead and make a PR and I can help with any other direction you might need and we can get it reviewed and merged!

And out of curiosity what's your use case that this was required? I always appreciate hearing about how my work is used.

Thanks again!

**Comment by gkjohnson** [comment]
See #428 

**TODO**
- [ ] Index no longer has to be ensured (`buildTree` function)
- [ ] Instead of bookkeeping an index array we keep an indirect "triangleIndex" array that is 1/3 the size (`buildTree` function)
- [ ] "partition" function needs to sort an array that is 1 / 3 the size (`partition` function)
- [ ] "raycast" function needs to be adjusted to take an indirect array or take function for running intersections (`raycast` cast function)
- [ ] "raycastFirst" function needs to be adjusted to take an indirect array or take function for running intersections (`raycastFirst` cast function)
- [ ] Worker generation / serialization
- [ ] "shapecast" functions needs to be adjusted to take an indirect array or it can be wrapped in MeshBVH call (`MeshBVH.shapecast` or `shapecast` cast function)
- [ ] Shader BVH packing needs to know about the indirect storage.
  - deindex the buffer here
- [ ] Adjust code to be agnostic to index presence.
- [ ] Tests
  - [ ] Randomized tests
  - [ ] Serialized tests
  - [ ] Removed index tests
  - [ ] Option tests

**Comment by gkjohnson** [comment]
Basics added in #555 

**Next**
- figure out option name, indirect field
- write more tests
   - ensure bvhcast is tested
- shave time off benchmark
  - remove tight inner conditionals
  - remove tight inner function calls
- documentation

**Comment by gkjohnson** [comment]
Fixed in #439
